[".vim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"
[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/fzf-tab"]
type = "archive"
url = "https://github.com/Aloxaf/fzf-tab/archive/refs/heads/master.zip"
exact = true
stripComponents = 1
refreshPeriod = "168h"
