#!/usr/bin/env bash
# shellcheck disable=all

zstyle ":completion:*" list-colors "\${(s.:.)LS_COLORS}"
zstyle ':completion:*' rehash true
zstyle ":completion:*" matcher-list \
  "m:{a-zA-Z}={A-Za-z}" \
  "r:|[._-]=* r:|=*" \
  "l:|=* r:|=*"

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=up:up,down:down
# To make fzf-tab follow FZF_DEFAULT_OPTS.
#zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

if command -v kubectl &>/dev/null; then
  # shellcheck disable=SC1090
  source <(kubectl completion zsh || true)
fi

if command -v gh &>/dev/null; then
  # shellcheck disable=SC1090
  source <(gh completion -s zsh || true)
fi

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

source "${HOME}/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh"
