# ~/.config/herdr/config.toml

[keys]
new_tab = "ctrl+alt+cmd+c"

split_vertical   = "ctrl+alt+cmd+i"
split_horizontal = "ctrl+alt+cmd+slash"
zoom             = "ctrl+alt+cmd+z"
resize_mode      = "ctrl+alt+cmd+r"
close_pane       = ["ctrl+alt+cmd+x", "ctrl+alt+cmd+w"]

focus_pane_left  = "ctrl+alt+cmd+left"
focus_pane_down  = "ctrl+alt+cmd+down"
focus_pane_up    = "ctrl+alt+cmd+up"
focus_pane_right = "ctrl+alt+cmd+right"

resize_pane_left  = "ctrl+alt+cmd+shift+left"
resize_pane_down  = "ctrl+alt+cmd+shift+down"
resize_pane_up    = "ctrl+alt+cmd+shift+up"
resize_pane_right = "ctrl+alt+cmd+shift+right"

switch_tab = "ctrl+alt+cmd+1..9"

previous_tab = "ctrl+alt+cmd+p"
next_tab     = "ctrl+alt+cmd+n"

rename_tab        = "ctrl+alt+cmd+comma"
move_tab_previous = "ctrl+alt+cmd+shift+comma"
move_tab_next     = "ctrl+alt+cmd+shift+period"

goto = "ctrl+alt+cmd+f"
