# Global config
add_newline = false
#format = "$directory $git_branch $git_state$git_status$git_metrics$character"
format = "$directory $git_branch$git_status$character "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
format = "$symbol"

[directory]
style = "bold blue"
truncate_to_repo = false
#truncation_length = 3
#truncation_symbol = "…/"
format = "[$path]($style)"

[git_branch]
style = "bold purple"
format = '([$branch]($style))'

[git_status]
disabled = false
style = "bold yellow"
format = "[$all_status $ahead_behind]($style)"
conflicted = "⚔"
#ahead = "⇡${count}"
#behind = "⇣${count}"
#diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
stashed = "s"
modified = "*"
staged = "+"
#renamed = "»"
#deleted = "✘"

[git_state]
style = "bold red"
format = " [$state( $progress_current/$progress_total)]($style)"

[git_metrics]
disabled = true
format = " ([+$added]($added_style) [-$deleted]($deleted_style))"
added_style = "bold green"
deleted_style = "bold red"
